### ISSUE TITLE
extracted netlist simulation doesn't match the schematic simulation.

### ISSUE THREAD

**Issue by MostafaAbdelrady** [mabrains/caravel_user_project_ldo#1]
https://github.com/mabrains/caravel_user_project_ldo/blob/main/gds/ldo_v1/ldo_v1_extracted.spi

also the netlist contains devices with zero area.

**Comment by atorkmabrains** [comment]
@MostafaAbdelrady That's most likely a bug in netgen. This is a netlist that was extracted from GDS. I'll close the issue

**Comment by atorkmabrains** [comment]
This netlist was used for LVS purposes.
